from django.urls import path
from . import views

urlpatterns = [
    path('connections/', views.server_connections, name='server_connections'),
    path('connections/create/', views.create_connection, name='create_connection'),
    path('connections/update/<int:connection_id>/', views.update_connection, name='update_connection'),
    path('connections/delete/<int:connection_id>/', views.delete_connection, name='delete_connection'),
    path('clusters/<int:connection_id>/', views.get_clusters, name='get_clusters'),
    path('clusters/<int:connection_id>/insert/', views.insert_cluster, name='insert_cluster'),
    path('clusters/<int:connection_id>/<str:cluster_uuid>/', views.get_cluster_details, name='get_cluster_details'),
    path('clusters/<int:connection_id>/<str:cluster_uuid>/update/', views.update_cluster, name='update_cluster'),
    path('clusters/<int:connection_id>/<str:cluster_uuid>/remove/', views.remove_cluster, name='remove_cluster'),
    path('sessions/<int:connection_id>/', views.get_sessions, name='get_sessions'),
    path('sessions/<int:connection_id>/<str:cluster_uuid>/info/', views.get_session_info, name='get_session_info'),
    path('sessions/terminate/', views.terminate_sessions, name='terminate_sessions'),
    path('sessions/interrupt/', views.interrupt_server_calls, name='interrupt_server_calls'),
    path('processes/<int:connection_id>/', views.get_processes, name='get_processes'),
    path('processes/<int:connection_id>/<str:cluster_uuid>/info/', views.get_process_info, name='get_process_info'),
    path('managers/<int:connection_id>/', views.get_managers, name='get_managers'),
    path('managers/<int:connection_id>/<str:cluster_uuid>/info/', views.get_manager_info, name='get_manager_info'),
    path('infobases/<int:connection_id>/', views.get_infobases, name='get_infobases'),
    path('infobases/<int:connection_id>/<str:cluster_uuid>/info/', views.get_infobase_info, name='get_infobase_info'),
    path('infobases/<int:connection_id>/<str:cluster_uuid>/create/', views.create_infobase, name='create_infobase'),
    path('infobases/<int:connection_id>/<str:cluster_uuid>/update/', views.update_infobase, name='update_infobase'),
    path('infobases/<int:connection_id>/<str:cluster_uuid>/drop/', views.drop_infobase, name='drop_infobase'),
    path('servers/<int:connection_id>/', views.get_servers, name='get_servers'),
    path('servers/<int:connection_id>/<str:cluster_uuid>/<str:server_uuid>/info/', views.get_server_info, name='get_server_info'),
    path('servers/<int:connection_id>/<str:cluster_uuid>/insert/', views.insert_server, name='insert_server'),
    path('servers/<int:connection_id>/<str:cluster_uuid>/<str:server_uuid>/update/', views.update_server, name='update_server'),
    path('servers/<int:connection_id>/<str:cluster_uuid>/<str:server_uuid>/remove/', views.remove_server, name='remove_server'),
    # Требования назначения функциональности (ТНФ)
    path('rules/<int:connection_id>/<str:cluster_uuid>/<str:server_uuid>/', views.get_rules, name='get_rules'),
    path('rules/<int:connection_id>/<str:cluster_uuid>/<str:server_uuid>/<str:rule_uuid>/info/', views.get_rule_info, name='get_rule_info'),
    path('rules/<int:connection_id>/<str:cluster_uuid>/<str:server_uuid>/create/', views.create_rule, name='create_rule'),
    path('rules/<int:connection_id>/<str:cluster_uuid>/<str:server_uuid>/<str:rule_uuid>/update/', views.update_rule, name='update_rule'),
    path('rules/<int:connection_id>/<str:cluster_uuid>/<str:server_uuid>/<str:rule_uuid>/delete/', views.delete_rule, name='delete_rule'),
    path('rules/<int:connection_id>/<str:cluster_uuid>/<str:server_uuid>/apply/', views.apply_rules, name='apply_rules'),
]