# Generated by Django 4.2.7 on 2025-12-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_force_password_change_profile_last_login_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject_to_password_policy',
            field=models.BooleanField(default=True, verbose_name='Подчиняется парольной политике'),
        ),
    ]
