# Generated by Django 4.2.7 on 2025-11-29 20:52

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='Отображаемое имя')),
                ('server_host', models.CharField(max_length=255, verbose_name='Сервер')),
                ('ras_port', models.IntegerField(verbose_name='Порт RAS')),
                ('cluster_admin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Логин кластера')),
                ('cluster_password', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль кластера'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usergroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Подключение к серверу',
                'verbose_name_plural': 'Подключения к серверам',
            },
        ),
    ]
