# Generated by Django 4.2.7 on 2025-12-09 15:36

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconnection',
            name='agent_password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль агента кластера')),
        ),
        migrations.AddField(
            model_name='serverconnection',
            name='agent_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Логин агента кластера'),
        ),
    ]
