# Generated by Django 4.2.7 on 2025-12-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('clusters', '0002_serverconnection_agent_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverconnection',
            options={'ordering': ['order', 'display_name'], 'verbose_name': 'Подключение к серверу', 'verbose_name_plural': 'Подключения к серверам'},
        ),
        migrations.AddField(
            model_name='serverconnection',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.CreateModel(
            name='ConnectionFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название папки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usergroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Папка подключений',
                'verbose_name_plural': 'Папки подключений',
                'ordering': ['order', 'name'],
                'unique_together': {('user_group', 'name')},
            },
        ),
        migrations.AddField(
            model_name='serverconnection',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clusters.connectionfolder', verbose_name='Папка'),
        ),
    ]
